import type { AgentToolConfig } from "@claake/shared";

export class AgentResponseDto {
	id!: string;
	name!: string;
	slug!: string;
	description!: string;
	long_description!: string | null;
	category!: string;
	tags!: string[];
	models!: string[];
	mode!: string;
	config_url!: string | null;
	image_url!: string | null;
	screenshots!: string[];
	pricing_model!: string;
	price!: number;
	credit_cost!: number;
	status!: string;
	permissions!: Record<string, unknown> | null;
	download_count!: number;
	rating!: number;
	review_count!: number;
	creator_id!: string;
	creator_name!: string | null;
	created_at!: string;
	updated_at!: string;
	system_prompt!: string | null;
	welcome_message!: string | null;
	suggested_prompts!: string[];
	limitations!: string[];
	model_settings!: Record<string, unknown> | null;
	capabilities!: Record<string, unknown> | null;
	variables!: Record<string, unknown> | null;
	few_shot_examples!: Record<string, unknown>[];
	output_format!: string | null;
	quality_checklist!: string[];
	tools!: AgentToolConfig[];
	cloud_strategy!: string | null;
	endpoint_format!: string | null;
	required_user_provider!: string | null;
	docker_image!: string | null;
	download_url!: string | null;
}
